---
- name: "Insert/Update /etc/profile"
  blockinfile:
    path: /etc/profile
    block: "{{ profile_main }}"
  when:
    - "profile_main is defined"
    - "profile_main|length > 0"

- name: "Add file in profile.d from config"
  ansible.builtin.copy:
    dest: "/etc/profile.d/{{ item.file }}"
    content: "{{ item.content }}"
    mode: '0644'
  with_items: "{{ profile_config }}"
  when: "(item.state is defined and item.state != 'absent') or (item.state is defined and item.state == 'present') or item.state is not defined"

- name: "Add external profile files"
  copy:
    src: "{{ item }}"
    dest: "/etc/profile.d/"
    mode: 0644
  with_fileglob: "{{ profile_files }}"
  when:
    - "profile_files is defined"

- name: "Remove file from profile.d"
  ansible.builtin.file:
    path: "/etc/profile.d/{{ item }}"
    state: absent
  with_items: "{{ profile_remove }}"
  when:
    - "profile_remove is defined"
